### ISSUE TITLE
Maven dependency does not exist

### ISSUE THREAD

**Issue by a-ammar** [kanthkumar46/GRAAL#4]
I was trying to run the GRAAL code but these two dependencies does not exits
<dependency>
            <groupId>edu.rit.capstone</groupId>
            <artifactId>libraries-support</artifactId>
            <version>${libraries-support.version}</version>
        </dependency>
        <dependency>
            <groupId>edu.rit.capstone</groupId>
            <artifactId>orbitcounter</artifactId>
            <version>${orbitcounter.version}</version>
        </dependency>

Can you check this please ?

Thanks

**Comment by kanthkumar46** [comment]
Hi Ammar, thanks for raising the issue. I haven't published those artifacts to any public maven repository. You can find the dependencies here: 
https://github.com/kanthkumar46/libraries-support
https://github.com/kanthkumar46/ORCA 

Please clone these repos and run "mvn clean install" to get the dependencies in your local maven repository.

**Comment by ammar257ammar** [comment]
Thank you so much for the reply. Problem Solved!!!
